/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eric_ndkapp_ServerActivity */

#ifndef _Included_com_eric_ndkapp_ServerActivity
#define _Included_com_eric_ndkapp_ServerActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_eric_ndkapp_ServerActivity_BIND_ABOVE_CLIENT
#define com_eric_ndkapp_ServerActivity_BIND_ABOVE_CLIENT 8L
#undef com_eric_ndkapp_ServerActivity_BIND_ADJUST_WITH_ACTIVITY
#define com_eric_ndkapp_ServerActivity_BIND_ADJUST_WITH_ACTIVITY 128L
#undef com_eric_ndkapp_ServerActivity_BIND_ALLOW_OOM_MANAGEMENT
#define com_eric_ndkapp_ServerActivity_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef com_eric_ndkapp_ServerActivity_BIND_AUTO_CREATE
#define com_eric_ndkapp_ServerActivity_BIND_AUTO_CREATE 1L
#undef com_eric_ndkapp_ServerActivity_BIND_DEBUG_UNBIND
#define com_eric_ndkapp_ServerActivity_BIND_DEBUG_UNBIND 2L
#undef com_eric_ndkapp_ServerActivity_BIND_IMPORTANT
#define com_eric_ndkapp_ServerActivity_BIND_IMPORTANT 64L
#undef com_eric_ndkapp_ServerActivity_BIND_NOT_FOREGROUND
#define com_eric_ndkapp_ServerActivity_BIND_NOT_FOREGROUND 4L
#undef com_eric_ndkapp_ServerActivity_BIND_WAIVE_PRIORITY
#define com_eric_ndkapp_ServerActivity_BIND_WAIVE_PRIORITY 32L
#undef com_eric_ndkapp_ServerActivity_CONTEXT_IGNORE_SECURITY
#define com_eric_ndkapp_ServerActivity_CONTEXT_IGNORE_SECURITY 2L
#undef com_eric_ndkapp_ServerActivity_CONTEXT_INCLUDE_CODE
#define com_eric_ndkapp_ServerActivity_CONTEXT_INCLUDE_CODE 1L
#undef com_eric_ndkapp_ServerActivity_CONTEXT_RESTRICTED
#define com_eric_ndkapp_ServerActivity_CONTEXT_RESTRICTED 4L
#undef com_eric_ndkapp_ServerActivity_MODE_APPEND
#define com_eric_ndkapp_ServerActivity_MODE_APPEND 32768L
#undef com_eric_ndkapp_ServerActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define com_eric_ndkapp_ServerActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef com_eric_ndkapp_ServerActivity_MODE_MULTI_PROCESS
#define com_eric_ndkapp_ServerActivity_MODE_MULTI_PROCESS 4L
#undef com_eric_ndkapp_ServerActivity_MODE_PRIVATE
#define com_eric_ndkapp_ServerActivity_MODE_PRIVATE 0L
#undef com_eric_ndkapp_ServerActivity_MODE_WORLD_READABLE
#define com_eric_ndkapp_ServerActivity_MODE_WORLD_READABLE 1L
#undef com_eric_ndkapp_ServerActivity_MODE_WORLD_WRITEABLE
#define com_eric_ndkapp_ServerActivity_MODE_WORLD_WRITEABLE 2L
#undef com_eric_ndkapp_ServerActivity_DEFAULT_KEYS_DIALER
#define com_eric_ndkapp_ServerActivity_DEFAULT_KEYS_DIALER 1L
#undef com_eric_ndkapp_ServerActivity_DEFAULT_KEYS_DISABLE
#define com_eric_ndkapp_ServerActivity_DEFAULT_KEYS_DISABLE 0L
#undef com_eric_ndkapp_ServerActivity_DEFAULT_KEYS_SEARCH_GLOBAL
#define com_eric_ndkapp_ServerActivity_DEFAULT_KEYS_SEARCH_GLOBAL 4L
#undef com_eric_ndkapp_ServerActivity_DEFAULT_KEYS_SEARCH_LOCAL
#define com_eric_ndkapp_ServerActivity_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef com_eric_ndkapp_ServerActivity_DEFAULT_KEYS_SHORTCUT
#define com_eric_ndkapp_ServerActivity_DEFAULT_KEYS_SHORTCUT 2L
#undef com_eric_ndkapp_ServerActivity_RESULT_CANCELED
#define com_eric_ndkapp_ServerActivity_RESULT_CANCELED 0L
#undef com_eric_ndkapp_ServerActivity_RESULT_FIRST_USER
#define com_eric_ndkapp_ServerActivity_RESULT_FIRST_USER 1L
#undef com_eric_ndkapp_ServerActivity_RESULT_OK
#define com_eric_ndkapp_ServerActivity_RESULT_OK -1L
#undef com_eric_ndkapp_ServerActivity_HONEYCOMB
#define com_eric_ndkapp_ServerActivity_HONEYCOMB 11L
#undef com_eric_ndkapp_ServerActivity_MSG_REALLY_STOPPED
#define com_eric_ndkapp_ServerActivity_MSG_REALLY_STOPPED 1L
#undef com_eric_ndkapp_ServerActivity_MSG_RESUME_PENDING
#define com_eric_ndkapp_ServerActivity_MSG_RESUME_PENDING 2L
/*
 * Class:     com_eric_ndkapp_ServerActivity
 * Method:    nativeStartServer
 * Signature: (Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_eric_ndkapp_ServerActivity_nativeStartServer
  (JNIEnv *, jobject, jstring, jint, jstring);

/*
 * Class:     com_eric_ndkapp_ServerActivity
 * Method:    nativeStopServer
 * Signature: (Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_eric_ndkapp_ServerActivity_nativeStopServer
  (JNIEnv *, jobject, jstring, jint, jstring);

/*
 * Class:     com_eric_ndkapp_ServerActivity
 * Method:    nativeSendServer
 * Signature: (Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_eric_ndkapp_ServerActivity_nativeSendServer
  (JNIEnv *, jobject, jstring, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_eric_ndkapp_ServerActivity_SendServerMessageTask */

#ifndef _Included_com_eric_ndkapp_ServerActivity_SendServerMessageTask
#define _Included_com_eric_ndkapp_ServerActivity_SendServerMessageTask
#ifdef __cplusplus
extern "C" {
#endif
#undef com_eric_ndkapp_ServerActivity_SendServerMessageTask_MIN_PRIORITY
#define com_eric_ndkapp_ServerActivity_SendServerMessageTask_MIN_PRIORITY 1L
#undef com_eric_ndkapp_ServerActivity_SendServerMessageTask_NORM_PRIORITY
#define com_eric_ndkapp_ServerActivity_SendServerMessageTask_NORM_PRIORITY 5L
#undef com_eric_ndkapp_ServerActivity_SendServerMessageTask_MAX_PRIORITY
#define com_eric_ndkapp_ServerActivity_SendServerMessageTask_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_eric_ndkapp_ServerActivity_StartServerTask */

#ifndef _Included_com_eric_ndkapp_ServerActivity_StartServerTask
#define _Included_com_eric_ndkapp_ServerActivity_StartServerTask
#ifdef __cplusplus
extern "C" {
#endif
#undef com_eric_ndkapp_ServerActivity_StartServerTask_MIN_PRIORITY
#define com_eric_ndkapp_ServerActivity_StartServerTask_MIN_PRIORITY 1L
#undef com_eric_ndkapp_ServerActivity_StartServerTask_NORM_PRIORITY
#define com_eric_ndkapp_ServerActivity_StartServerTask_NORM_PRIORITY 5L
#undef com_eric_ndkapp_ServerActivity_StartServerTask_MAX_PRIORITY
#define com_eric_ndkapp_ServerActivity_StartServerTask_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_eric_ndkapp_ServerActivity_StopServerTask */

#ifndef _Included_com_eric_ndkapp_ServerActivity_StopServerTask
#define _Included_com_eric_ndkapp_ServerActivity_StopServerTask
#ifdef __cplusplus
extern "C" {
#endif
#undef com_eric_ndkapp_ServerActivity_StopServerTask_MIN_PRIORITY
#define com_eric_ndkapp_ServerActivity_StopServerTask_MIN_PRIORITY 1L
#undef com_eric_ndkapp_ServerActivity_StopServerTask_NORM_PRIORITY
#define com_eric_ndkapp_ServerActivity_StopServerTask_NORM_PRIORITY 5L
#undef com_eric_ndkapp_ServerActivity_StopServerTask_MAX_PRIORITY
#define com_eric_ndkapp_ServerActivity_StopServerTask_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
